### ISSUE TITLE
python main.py

### ISSUE THREAD

**Issue by KirillHiddleston** [swhan0329/erp_inpainting#2]
```
parser.add_argument("--data_dir", default="../../data/building_json_256/Small", type=str, dest="data_dir")

parser.add_argument("--ckpt_dir", default="./checkpoint_s256", type=str, dest="ckpt_dir")
parser.add_argument("--log_dir", default="./log_s256", type=str, dest="log_dir")
parser.add_argument("--result_dir", default="./result_s256", type=str, dest="result_dir")

parser.add_argument("--input_img", default="./test/image/0006_test.png", type=str, dest="input_img")
parser.add_argument("--input_msk", default="./test/mask/0006_mask.png", type=str, dest="input_msk")
parser.add_argument("--outdir_json", default="./test", type=str, dest="outdir_json")
```
--data_dir - it path to "jsone" creat from image ?
--input_img  - why u show path to only one img

please explain to me more about the paths in main.py

**Comment by swhan0329** [comment]
Hello, @KirillHiddleston.

1. Is the path to "JSON" create from images?
- This path means the path of the JSON file that reads multiple images and masks into one JSON file.
([how to make a JSON file](https://github.com/swhan0329/panorama_image_inpainting/tree/fb6a48c281b194dd51158e76e5aa9b071b01fa35#pre-processing))
2. Why do you show the path to only one img?
- I made several original images and several masks into one JSON file and trained the network using this one JSON file. The input_img used here is the image used during inference.
