### ISSUE TITLE
create data

### ISSUE THREAD

**Issue by Tg-12224** [swhan0329/erp_inpainting#3]
I would like to ask a question about creating data.When I run the create_data.py file, there will be an error in dataset.py,prompt me that an error occurred: KeyError:'pano'. When creating the data, 'pano'was not saved in the json file,Is this something wrong with the way I created the data?

**Comment by swhan0329** [comment]
@Tg-12224 Thank you for your interest. It will very helpful if you upload your terminal. I want to see the exact error message. Could u do that for me?

**Comment by Tg-12224** [comment]
`Traceback (most recent call last):
  File "/home/lgn/Desktop/Code/inpainting/data/dataset.py", line 165, in <module>
    sample = transformed_dataset[i]
  File "/home/lgn/Desktop/Code/inpainting/data/dataset.py", line 53, in __getitem__
    sample_pano_img.append(b64utf82ndarr(in_json['pano']['pano'][0]))

KeyError: 'pano'`


I created the rectangle mask first, and then ran create_data.py to create a json file. An error occurred when running dataset.py, and the same error occurred in train.py.

**Comment by swhan0329** [comment]
@Tg-12224 okay.
This project is pretty old. So I don't know exactly what is problem.

But can u see some json files? 
You should double check what is key and value.
That error said there is no 'pano' key value.
If u are hard to see json file, you can upload json file too.

**Comment by Tg-12224** [comment]
I can see the json file, but there is no key'pano' in this file, I think it is not saved to the key'pano' in create_data.py

-i is the panorama in the data set, -m is the mask of the rectangle, is there something wrong with the way I create the json file?

**Comment by swhan0329** [comment]
@Tg-12224 In https://github.com/swhan0329/panorama_image_inpainting/blob/fb6a48c281b194dd51158e76e5aa9b071b01fa35/pre_proc/create_data.py#L101, if there is mask_dir exists pano key will create. If not there is no pano key I think.

Did u have/use mask_dir?

**Comment by Tg-12224** [comment]
I have mask_dir,and in the json file I created, I can see that there are'f_name' and'mask_flag' and'cube'and cube faces and their masks.

**Comment by swhan0329** [comment]
@Tg-12224 Please send me your output json file. And what command did you use for making create_data.py? Show me.

**Comment by Tg-12224** [comment]
[outputfile.zip](https://github.com/swhan0329/panorama_image_inpainting/files/7293280/outputfile.zip)
 
-i
../../dataset/panoramas_dataset
-m
../mask/rectangle-mask
-o
../data/output_dir/train1

Is such that?

**Comment by swhan0329** [comment]
```
def save_image(inp_path, output_dir, mask_path=None, face_w=128):
    pano_img = Image.open(inp_path, "r")
    inp_np = np.asarray(pano_img)

    base_name, _ = os.path.splitext(os.path.basename(inp_path))

    out_dict = dict()
    out_dict['f_name'] = inp_path
    out_dict['mask_flag'] = False

    face_list = ['f', 'r', 'b', 'l', 't', 'd']

    if mask_path is not None:
        img_mask = Image.open(mask_path, "r")
        inp_np_mask = np.asarray(img_mask)
        cm_mask, cl_mask = e2c(inp_np_mask, face_w=face_w)
        out_dict['mask_flag'] = True

    pano_imgs = dict()
    b_string = ndarr2b64utf8(inp_np)
    if mask_path is None:
        pano_imgs['pano'] = [b_string]
        
    else:
        b_string_mask = ndarr2b64utf8(inp_np_mask)
        pano_imgs['pano'] = [b_string]
        pano_imgs['pano_mask']=[b_string_mask]
    
    out_dict['pano'] = pano_imgs

    cm, cl = e2c(inp_np, face_w=face_w)
    
    cube_imgs = dict()

    for idx, face in enumerate(cl):
        b_string = ndarr2b64utf8(face)
        if mask_path is None:
            cube_imgs[face_list[idx]] = [b_string]
        else:
            b_string_mask = ndarr2b64utf8(cl_mask[idx])
            cube_imgs[face_list[idx]] = [b_string]
            cube_imgs[str(face_list[idx])+'_mask']=[b_string_mask]
    
    out_dict['cube'] = cube_imgs
    with open(os.path.join(output_dir, base_name + ".json"), "w") as f:
        json.dump(out_dict, f)
```
       
@Tg-12224 Oh I deleted some lines in create_data.py
This code will help you.

**Comment by Tg-12224** [comment]
https://github.com/swhan0329/panorama_image_inpainting/blob/fb6a48c281b194dd51158e76e5aa9b071b01fa35/train.py#L156
https://github.com/swhan0329/panorama_image_inpainting/blob/fb6a48c281b194dd51158e76e5aa9b071b01fa35/train.py#L158
https://github.com/swhan0329/panorama_image_inpainting/blob/fb6a48c281b194dd51158e76e5aa9b071b01fa35/train.py#L535
https://github.com/swhan0329/panorama_image_inpainting/blob/fb6a48c281b194dd51158e76e5aa9b071b01fa35/train.py#L536

Thank you very much for your code, I have solved the problem, there is another problem, I did not find the definition of these four functions

**Comment by swhan0329** [comment]
@Tg-12224 My bad.
Actually, this project is my first deep learning project. So I didn't save my files well.
face_load, cube_load, face_save, cube_sace is pretty close to load, save function in utils/util.py.
I don't have the next version of utils/util.py, sorry for that.

I just change some parameters of the load, save function. 
If you are familiar with PyTorch, you can write functions by yourself.
You can pull requests about that.

Thank you for your interest, again.

**Comment by Tg-12224** [comment]
Thank you for your help, it is very useful for me

**Comment by Zwhy0712** [comment]
> Actually, this project is my first deep learning project. So I didn't save my files well. face_load, cube_load, face_save, cube_sace is pretty close to load, save function in utils/util.py. I don't have the next version of utils/util.py, sorry for that.
> 
> I just change some parameters of the load, save function. If you are familiar with PyTorch, you can write functions by yourself. You can pull requests about that.
> 
> Thank you for your interest, again.

I would like to ask if the four functions have been written?

**Comment by swhan0329** [comment]
@123scott Can you tell me what is 'four functions'?

**Comment by Zwhy0712** [comment]
> @123scott Can you tell me what is 'four functions'?

![屏幕截图 2022-04-20 155311](https://user-images.githubusercontent.com/49402246/164178762-ff13d936-173e-4924-85a1-f4de1cd68c4b.png)

**Comment by swhan0329** [comment]
@123scott You can see that functions in utils/util.py. I don't test this code, but I think it will run well.
Feel free to ask me anything.

**Comment by Zwhy0712** [comment]
> @123scott You can see that functions in utils/util.py. I don't test this code, but I think it will run well. Feel free to ask me anything.

Sorry, I'm not very good at writing these four functions by myself, and the addition of my own is unsuccessful.

**Comment by swhan0329** [comment]
@123scott Please pull new master branch. I uploaded that functions today.

**Comment by Zwhy0712** [comment]
> @123scott Please pull new master branch. I uploaded that functions today.

thanks

**Comment by Tg-12224** [comment]
> @123scott Please pull new master branch. I uploaded that functions today.

could you tell me how long you have been training this program and how many epochs

**Comment by swhan0329** [comment]
@Tg-12224 I used a 2070 ti GPU and it took a week maybe. I cannot remember well.
