### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by Tg-12224** [swhan0329/erp_inpainting#5]
https://github.com/swhan0329/panorama_image_inpainting/blob/fb6a48c281b194dd51158e76e5aa9b071b01fa35/train.py#L608

Hello, I want to ask about the test network. I did not find this PInet_new in the model file, there is no way to test

**Comment by swhan0329** [comment]
@Tg-12224 Hello,
You can just change like below:
https://github.com/swhan0329/panorama_image_inpainting/blob/0e138d288bce0b2e3ffcea67506ac7200db0ed72/train.py#L608

I changed the code. Thank you for finding my error.

**Comment by Tg-12224** [comment]
The netG network in the test net, is it FaceG or CubeG?

**Comment by swhan0329** [comment]
@Tg-12224 Opss.
Lots of things need to change.
I updated my code. But I didn't debug because I don't have this environment for testing.
Could you check my code? And if you want to change my code, please do pull the request. 

Thank u for your attention again.
