### ISSUE TITLE
data processing

### ISSUE THREAD

**Issue by Zwhy0712** [swhan0329/erp_inpainting#6]
Hi, your work is really great. thanks
I would like to ask if there is a panorama image to cube map and processing in this?

**Comment by swhan0329** [comment]
@123scott Hello, thank you for your interest :)

https://github.com/swhan0329/panorama_image_inpainting/blob/9efaf5f3836b365d33db66ab7878fc0e20bdcec2/pre_proc/create_data.py

In the above file, you can check what you want.

First, you should download the panorama image from the URL in the README.md.
Second, use the above file. If there is no mask, save just a cube map image.
